using System.Text;
using Microsoft.Extensions.Logging;
using NetFirewall.Models;
using NetFirewall.Models.Network;
using NetFirewall.Models.System;
using NetFirewall.Services.Processes;

namespace NetFirewall.Services.Network;

/// <summary>
/// Writes /etc/unbound/unbound.conf.d/netfirewall.conf and restarts unbound.service
/// (or stops it when the config disables forwarding). All side effects are gated
/// on the kernel's view of unbound being installed — if it isn't, the apply still
/// "succeeds" with a logged note instead of throwing, so the wizard can complete
/// on hosts where the operator hasn't installed unbound yet.
/// </summary>
public sealed class UnboundForwarderService : IDnsForwarderService
{
    private const string ConfDir   = "/etc/unbound/unbound.conf.d";
    private const string ConfFile  = "/etc/unbound/unbound.conf.d/netfirewall.conf";
    private const string ServiceUnit = "unbound";

    private readonly IProcessRunner _runner;
    private readonly ILogger<UnboundForwarderService> _logger;

    public UnboundForwarderService(IProcessRunner runner, ILogger<UnboundForwarderService> logger)
    {
        _runner = runner;
        _logger = logger;
    }

    public async Task<ServiceResponse<NetworkApplyResult>> ApplyAsync(DnsForwarderConfig config, CancellationToken ct = default)
    {
        // No-op path: feature toggled off in the wizard. Stop the service if it's
        // running so we don't leave a stale forwarder behind, but don't fail the
        // wizard apply when the service simply isn't installed.
        if (!config.Enabled)
        {
            if (File.Exists(ConfFile)) File.Delete(ConfFile);
            var stop = await _runner.RunAsync("systemctl", $"stop {ServiceUnit}", TimeSpan.FromSeconds(15), ct);
            _logger.LogInformation("DNS forwarder disabled — removed conf, stop exit {Exit}", stop.ExitCode);
            return ServiceResponse<NetworkApplyResult>.Ok(
                new NetworkApplyResult { Success = true, Message = "DNS forwarder disabled.", ExitCode = 0 },
                "DNS forwarder disabled.");
        }

        if (string.IsNullOrWhiteSpace(config.UpstreamDns1))
            return ServiceResponse<NetworkApplyResult>.Fail("UpstreamDns1 is required when the forwarder is enabled.");

        try
        {
            Directory.CreateDirectory(ConfDir);
        }
        catch (DirectoryNotFoundException)
        {
            // /etc/unbound doesn't exist → unbound isn't installed. Surface a clear message instead of a stack trace.
            return ServiceResponse<NetworkApplyResult>.Fail(
                "/etc/unbound is missing. Install the 'unbound' package (apt install unbound) and re-run apply.");
        }

        var conf = RenderConfig(config);
        await File.WriteAllTextAsync(ConfFile, conf, ct);
        _logger.LogInformation("Wrote unbound forwarder conf to {Path} ({Bytes} bytes)", ConfFile, conf.Length);

        // checkconf catches syntax issues before we restart; bails the apply if it returns non-zero.
        var check = await _runner.RunAsync("unbound-checkconf", string.Empty, TimeSpan.FromSeconds(15), ct);
        if (!check.Success)
        {
            return ServiceResponse<NetworkApplyResult>.Fail(
                $"unbound-checkconf failed (exit {check.ExitCode}): {check.Error?.Trim()}");
        }

        var restart = await _runner.RunAsync("systemctl", $"restart {ServiceUnit}", TimeSpan.FromSeconds(20), ct);
        var ok = restart.Success;
        var msg = ok
            ? $"unbound restarted (exit {restart.ExitCode})."
            : $"systemctl restart {ServiceUnit} failed (exit {restart.ExitCode}): {restart.Error?.Trim()}";

        var result = new NetworkApplyResult
        {
            Success = ok,
            Message = msg,
            ExitCode = restart.ExitCode
        };
        return ok ? ServiceResponse<NetworkApplyResult>.Ok(result, msg)
                  : ServiceResponse<NetworkApplyResult>.Fail(msg);
    }

    private static string RenderConfig(DnsForwarderConfig c)
    {
        var allowed = (c.AllowedClients is { Count: > 0 })
            ? c.AllowedClients
            : new[] { "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "127.0.0.0/8" };

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by NetFirewall — do not edit manually.");
        sb.AppendLine("server:");
        sb.AppendLine("    interface: 0.0.0.0");
        sb.AppendLine($"    port: {c.ListenPort}");
        sb.AppendLine("    do-ip4: yes");
        sb.AppendLine("    do-udp: yes");
        sb.AppendLine("    do-tcp: yes");
        sb.AppendLine("    hide-identity: yes");
        sb.AppendLine("    hide-version: yes");
        sb.AppendLine("    qname-minimisation: yes");
        sb.AppendLine("    harden-glue: yes");
        sb.AppendLine("    harden-dnssec-stripped: yes");
        sb.AppendLine("    use-caps-for-id: yes");
        sb.AppendLine("    prefetch: yes");
        sb.AppendLine("    cache-min-ttl: 60");
        sb.AppendLine("    cache-max-ttl: 86400");
        foreach (var net in allowed)
            sb.AppendLine($"    access-control: {net} allow");
        sb.AppendLine();
        sb.AppendLine("forward-zone:");
        sb.AppendLine("    name: \".\"");
        sb.AppendLine($"    forward-addr: {c.UpstreamDns1}");
        if (!string.IsNullOrWhiteSpace(c.UpstreamDns2))
            sb.AppendLine($"    forward-addr: {c.UpstreamDns2}");
        return sb.ToString();
    }
}
