-- 00014_wireguard.sql
-- WireGuard server + peers. Single-server design: most home/SOHO firewalls
-- only need one wg0; multi-server is a future iteration. Peer keys are
-- generated by the daemon (wg genkey/pubkey) and the PRIVATE key is shown
-- to the operator once at creation time then thrown away — only the public
-- key persists, matching how every WireGuard front-end works.

CREATE TABLE IF NOT EXISTS wg_servers (
    id            uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    name          varchar(64)  NOT NULL DEFAULT 'wg0',
    private_key   text         NOT NULL,                    -- base64, 44 chars
    public_key    text         NOT NULL,                    -- base64, derived
    listen_port   int          NOT NULL DEFAULT 51820,
    address_cidr  text         NOT NULL,                    -- e.g. 10.10.0.1/24
    post_up       text,                                     -- iptables/nft hook (optional)
    post_down     text,
    enabled       boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT NOW(),
    updated_at    timestamptz  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wg_peers (
    id                     uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    server_id              uuid         NOT NULL REFERENCES wg_servers(id) ON DELETE CASCADE,
    name                   varchar(80)  NOT NULL,
    public_key             text         NOT NULL,             -- peer's pubkey (we never store its privkey)
    preshared_key          text,                              -- optional
    allowed_ips            text[]       NOT NULL DEFAULT '{}',-- e.g. {10.10.0.2/32}
    persistent_keepalive   int,                               -- seconds; null = off
    description            text,
    enabled                boolean      NOT NULL DEFAULT true,
    created_at             timestamptz  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wg_peers_server  ON wg_peers (server_id);
CREATE INDEX IF NOT EXISTS idx_wg_peers_enabled ON wg_peers (enabled);
